[package]
name = "reddit-client-gtk-rs"
version = "0.1.0"
authors = ["Johan Bjäreholt <johan@bjareho.lt>"]
edition = "2018"

[dependencies]
redditor = { git = "https://github.com/johan-bjareholt/redditor.git" }
webkit2gtk = "0.5"
glib = "0.6"

[dependencies.gtk]
version = "0.5"
features = ["v3_22"]
