[package]
name = "reddit-client-gtk-rs"
version = "0.1.0"
authors = ["Johan Bjäreholt <johan@bjareho.lt>"]
edition = "2018"

[dependencies]
rawr = { git = "https://github.com/johan-bjareholt/rawr.git" }
glib = "0.6.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_22"]
